In [2]:
pip install numpy

Requirement already satisfied: numpy in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (1.26.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install pandas

Requirement already satisfied: pandas in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as np 
import pandas as pd

In [5]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies=movies.merge(credits,on='title')

In [9]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
# which column should we keep ?  it should be based on content, genre, poster id, keywords, language, title, overwiewj, popularity, cast, crew
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [11]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [12]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:
movies.duplicated().sum()

0

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
# i want this '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]' to be like this ['Action','adventure', and etc]

In [18]:
import ast

genres_str = '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

genres_list = ast.literal_eval(genres_str)

print(genres_list)

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]

In [19]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [20]:
movies['genres']=movies['genres'].apply(convert)

In [21]:
movies['keywords']=movies['keywords'].apply(convert)

In [22]:
def convert5(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=5:
            l.append(i['name'])
            counter+=1
        else:
            break
    return l

In [23]:
movies['cast']=movies['cast'].apply(convert5)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
def fetch_director(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i['job']== 'Director':
      L.append(i['name'])
      break
  return L

In [26]:
movies['crew']= movies['crew'].apply(fetch_director)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [28]:
movies['overview']=movies['overview'].apply(lambda x : x.split())

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [30]:
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object

In [31]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [33]:
movies['tags']=movies['overview'] + movies['genres'] + movies['cast']+ movies['crew']

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [35]:
new_df=movies[['movie_id','title','tags']]

In [36]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [37]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_64201/487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [38]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [39]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez JamesCameron'

In [40]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_64201/4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [41]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [42]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez jamescameron'

In [43]:
new_df['tags'][1]

'captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action johnnydepp orlandobloom keiraknightley stellanskarsgÃ¥rd chowyun-fat goreverbinski'

In [44]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from scikit-learn) (1.26.3)
Requirement already satisfied: scipy>=1.5.0 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from scikit-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample data
descriptions = [
    "In the 22nd century, a paraplegic marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action adventure fantasy science fiction.",
    "Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure fantasy action."
]

# TF-IDF vectorization
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(descriptions)

# Compute cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Print the similarity matrix
print(cosine_sim)

[[1.         0.23887461]
 [0.23887461 1.        ]]

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample data
descriptions = [
    "In the 22nd century, a paraplegic marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action adventure fantasy science fiction.",
    "Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure fantasy action."
]

# Query movie description
query_description = "A marine faces a unique mission on the moon Pandora and must choose between following orders and protecting an alien civilization. Adventure and conflict ensue."

# TF-IDF vectorization
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(descriptions)

# Compute cosine similarity between query and existing descriptions
cosine_sim_query = cosine_similarity(vectorizer.transform([query_description]), tfidf_matrix)[0]

# Set a similarity threshold (you can adjust this based on your preference)
similarity_threshold = 0.5

# Check if similarity is above the threshold
similar_movies = [index for index, sim in enumerate(cosine_sim_query) if sim > similarity_threshold]

# Print the result
if similar_movies:
    print(f"The movie description is similar to movies {similar_movies}.")
else:
    print("No similar movies found.")

The movie description is similar to movies [0].

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample data
description1 = "In the 22nd century, a paraplegic marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action adventure fantasy science fiction."

description2 = "Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure fantasy action."

# TF-IDF vectorization
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([description1, description2])

# Compute cosine similarity between the two descriptions
cosine_similarities = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1]).flatten()

# Set a similarity threshold (you can adjust this based on your preference)
similarity_threshold = 0.5

# Print the result
if cosine_similarities[0] > similarity_threshold:
    print("The movie descriptions are similar.")
else:
    print("The movie descriptions are not similar.")

The movie descriptions are not similar.

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000,stop_words='english')

In [49]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [50]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [51]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [52]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [53]:
feature_names = cv.get_feature_names_out()

In [54]:
feature_names

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [55]:
pip install nltk

Requirement already satisfied: nltk in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (3.8.1)
Requirement already satisfied: click in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in /Users/balajik/anaconda3/envs/machine-learning/lib/python3.11/site-packages (from nltk) (4.66.1)
Note: you may need to restart the kernel to use updated packages.

In [56]:
import nltk

In [57]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [58]:
def stem(text): 
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [59]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [60]:
ps.stem('loving')

'love'

In [61]:
ps.stem('dancing')

'danc'

In [62]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav stephenlang michellerodriguez jamescameron'

In [63]:
new_df['tags']=new_df['tags'].apply(stem)

/tmp/ipykernel_64201/3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [64]:
feature_names

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
cosine_similarity(vectors)

array([[1.        , 0.13636364, 0.0805823 , ..., 0.        , 0.        ,
        0.        ],
       [0.13636364, 1.        , 0.0805823 , ..., 0.03413944, 0.        ,
        0.        ],
       [0.0805823 , 0.0805823 , 1.        , ..., 0.03026138, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03413944, 0.03026138, ..., 1.        , 0.08006408,
        0.0270666 ],
       [0.        , 0.        , 0.        , ..., 0.08006408, 1.        ,
        0.05634362],
       [0.        , 0.        , 0.        , ..., 0.0270666 , 0.05634362,
        1.        ]])

In [67]:
cosine_similarity(vectors).shape

(4806, 4806)

In [68]:
similarity=cosine_similarity(vectors)

In [69]:
similarity[0]

array([1.        , 0.13636364, 0.0805823 , ..., 0.        , 0.        ,
       0.        ])

In [70]:
similarity[1]

array([0.13636364, 1.        , 0.0805823 , ..., 0.03413944, 0.        ,
       0.        ])

In [71]:
sorted(similarity[0],reverse=True)

[0.9999999999999999,
 0.24618298195866548,
 0.24618298195866548,
 0.23836564731139806,
 0.23652495839563303,
 0.2302830932359191,
 0.22975187432024505,
 0.21320071635561041,
 0.20683507599800763,
 0.20483662259967564,
 0.2022599587389726,
 0.2022599587389726,
 0.20145574100634503,
 0.20145574100634503,
 0.20100756305184242,
 0.20100756305184242,
 0.20100756305184242,
 0.19943100880436643,
 0.19462473604038072,
 0.19284730395996746,
 0.19069251784911845,
 0.19069251784911845,
 0.19069251784911845,
 0.19069251784911845,
 0.18953562637585883,
 0.18844459036110223,
 0.18659112407133685,
 0.18609684207969415,
 0.18609684207969415,
 0.18556740475630137,
 0.1818181818181818,
 0.18018749253911176,
 0.17782168978975482,
 0.17782168978975482,
 0.17766726362967533,
 0.17766726362967533,
 0.17571222379722679,
 0.17407765595569785,
 0.17407765595569785,
 0.17407765595569785,
 0.17407765595569785,
 0.17094086468945693,
 0.1706971854997297,
 0.1706971854997297,
 0.17056057308448835,
 0.17056057308448835,
 0.17056057308448835,
 0.17056057308448835,
 0.17056057308448835,
 0.16854996561581048,
 0.16854996561581048,
 0.16724840200141816,
 0.16724840200141816,
 0.16724840200141816,
 0.16648178955300671,
 0.16514456476895406,
 0.16412198797244362,
 0.16412198797244362,
 0.16256402219058874,
 0.16116459280507603,
 0.16116459280507603,
 0.16116459280507603,
 0.1599005372667078,
 0.1599005372667078,
 0.1599005372667078,
 0.1599005372667078,
 0.1586657656043835,
 0.15836151649297914,
 0.15836151649297914,
 0.15569978883230456,
 0.15569978883230456,
 0.15569978883230456,
 0.15569978883230456,
 0.1554926033927807,
 0.1554926033927807,
 0.15512630699850571,
 0.15512630699850571,
 0.15512630699850571,
 0.15512630699850571,
 0.15512630699850571,
 0.15512630699850571,
 0.15512630699850571,
 0.15386436372416593,
 0.1531679162134967,
 0.1531679162134967,
 0.1531679162134967,
 0.1531679162134967,
 0.15228622596829314,
 0.15075567228888181,
 0.15075567228888181,
 0.15075567228888181,
 0.15075567228888181,
 0.15075567228888181,
 0.15075567228888181,
 0.1507556722888818,
 0.1507556722888818,
 0.1507556722888818,
 0.1507556722888818,
 0.1484539238050411,
 0.14673479641335552,
 0.14673479641335552,
 0.14673479641335552,
 0.14673479641335552,
 0.14673479641335552,
 0.14673479641335552,
 0.14673479641335552,
 0.14673479641335552,
 0.14642685316435566,
 0.14642685316435566,
 0.1462544848254261,
 0.1462544848254261,
 0.1462544848254261,
 0.1462544848254261,
 0.1462544848254261,
 0.14414999403128942,
 0.14414999403128942,
 0.14414999403128942,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14245072057454744,
 0.14213381090374028,
 0.14213381090374028,
 0.14213381090374028,
 0.14213381090374028,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13957263155977062,
 0.13834289277321493,
 0.13834289277321493,
 0.13834289277321493,
 0.13655774839978377,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.13636363636363635,
 0.1348399724926484,
 0.1348399724926484,
 0.1348399724926484,
 0.1333662673423161,
 0.1333662673423161,
 0.1333662673423161,
 0.1333662673423161,
 0.1333662673423161,
 0.1333662673423161,
 0.1333662673423161,
 0.1333662673423161,
 0.13318543164240537,
 0.1305582419667734,
 0.1305582419667734,
 0.1305582419667734,
 0.1305582419667734,
 0.1305582419667734,
 0.1305582419667734,
 0.1305582419667734,
 0.1305582419667734,
 0.1305582419667734,
 0.130051217752471,
 0.130051217752471,
 0.12856486930664499,
 0.12856486930664499,
 0.12792042981336627,
 0.12792042981336627,
 0.12792042981336627,
 0.12792042981336627,
 0.12792042981336627,
 0.12712834523274563,
 0.12712834523274563,
 0.1257389226923863,
 0.1257389226923863,
 0.1254363015010636,
 0.1254363015010636,
 0.1254363015010636,
 0.1254363015010636,
 0.1254363015010636,
 0.1254363015010636,
 0.1254363015010636,
 0.12439408271422457,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933274,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12309149097933272,
 0.12087344460380703,
 0.12087344460380703,
 0.12087344460380703,
 0.12087344460380703,
 0.12087344460380703,
 0.12087344460380703,
 0.12087344460380703,
 0.12087344460380703,
 0.12060453783110543,
 0.1194162868053064,
 0.11877113736973435,
 0.11877113736973435,
 0.11877113736973435,
 0.11877113736973435,
 0.11877113736973435,
 0.11877113736973435,
 0.11877113736973435,
 0.11826247919781652,
 0.11826247919781652,
 0.11826247919781652,
 0.11826247919781652,
 0.11826247919781652,
 0.11826247919781652,
 0.11826247919781652,
 0.11677484162422842,
 0.11677484162422842,
 0.11677484162422842,
 0.11677484162422842,
 0.11677484162422842,
 0.11677484162422842,
 0.11677484162422842,
 0.11677484162422842,
 0.11605177063713189,
 0.1149919149152138,
 0.11487593716012254,
 0.11487593716012254,
 0.11487593716012254,
 0.11487593716012254,
 0.11487593716012254,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11396057645963795,
 0.11306675421666135,
 0.11306675421666135,
 0.11306675421666135,
 0.11306675421666135,
 0.11306675421666135,
 0.11306675421666133,
 0.112956498944981,
 0.11197850219117084,
 0.11134044285378084,
 0.11134044285378084,
 0.11134044285378084,
 0.11134044285378084,
 0.11134044285378084,
 0.11134044285378084,
 0.11134044285378084,
 0.11134044285378084,
 0.11134044285378084,
 0.11102547633067379,
 0.11102547633067379,
 0.11009637651263604,
 0.11009637651263604,
 0.11009637651263604,
 0.11009637651263604,
 0.11009637651263604,
 0.11009637651263604,
 0.11009637651263604,
 0.10969086361906957,
 0.10969086361906957,
 0.10969086361906957,
 0.10969086361906957,
 0.10969086361906957,
 0.10969086361906957,
 0.10969086361906957,
 0.10830607221477646,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10811249552346706,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10577717706958902,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.1037571695799112,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10341753799900381,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983783,
 0.10241831129983782,
 0.1019294382875251,
 0.1011299793694863,
 0.1011299793694863,
 0.1011299793694863,
 0.1011299793694863,
 0.1011299793694863,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.09988907373180403,
 0.09988907373180403,
 0.09988907373180403,
 0.09988907373180403,
 0.09988907373180403,
 0.09988907373180403,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09869275424396534,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09782319760890368,
 0.09753841331435326,
 0.09753841331435326,
 0.09753841331435326,
 0.09753841331435326,
 0.09753841331435326,
 0.09642365197998375,
 0.09642365197998373,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09329556203566843,
 0.09329556203566843,
 0.09329556203566843,
 0.09329556203566843,
 0.09329556203566843,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09304842103984708,
 0.09231861823449955,
 0.09231861823449955,
 0.09137173558097589,
 0.09137173558097589,
 0.09137173558097589,
 0.09137173558097589,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.0909090909090909,
 0.09045340337332908,
 0.09045340337332908,
 0.09045340337332908,
 0.09045340337332908,
 0.08989331499509894,
 0.0895622151039798,
 0.0895622151039798,
 0.0895622151039798,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08891084489487741,
 0.08869685939836239,
 0.08869685939836239,
 0.0878561118986134,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784891,
 0.08624393618641035,
 0.08624393618641035,
 0.08624393618641035,
 0.08624393618641035,
 0.08547043234472845,
 0.08547043234472845,
 0.08547043234472845,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08528028654224418,
 0.08471737420873575,
 0.08471737420873575,
 0.08444006618414981,
 0.08398387664337813,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08362420100070908,
 0.08257228238447703,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08206099398622181,
 0.08189266356489211,
 0.08189266356489211,
 0.08122955416108235,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.08058229640253801,
 0.0799502686333539,
 0.07933288280219176,
 0.07933288280219176,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07918075824648957,
 0.07850686719788597,
 0.07813983916059347,
 0.07813983916059347,
 0.07813983916059347,
 0.07813983916059347,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07784989441615228,
 0.07756315349925286,
 0.0769990503509018,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07658395810674835,
 0.07590680990538862,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.0753778361444409,
 0.07485976927589244,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07422696190252055,
 0.07336739820667776,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07312724241271305,
 0.07288942961247938,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07207499701564471,
 0.07150969419341942,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07033799484533299,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.06978631577988531,
 0.06978631577988531,
 0.06937459350943204,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06917144638660747,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06827887419989188,
 0.06818181818181818,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.06659271582120269,
 0.06659271582120269,
 0.06659271582120269,
 0.06659271582120269,
 0.06659271582120269,
 0.06659271582120269,
 0.06659271582120269,
 0.06596992457003137,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0657951694959769,
 0.0650256088762355,
 0.0650256088762355,
 0.0650256088762355,
 0.0650256088762355,
 0.0650256088762355,

In [72]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:11]

[(1444, 0.24618298195866548),
 (4405, 0.24618298195866548),
 (1194, 0.23836564731139806),
 (151, 0.23652495839563303),
 (3608, 0.2302830932359191),
 (942, 0.22975187432024505),
 (4348, 0.21320071635561041),
 (4010, 0.20683507599800763),
 (7, 0.20483662259967564),
 (2999, 0.2022599587389726)]

In [73]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:11]

    for i in movies_list:
        new_df.iloc[i[0]].title
        print(new_df.iloc[i[0]].title)

In [74]:
recommend('Batman Begins')

The Dark Knight Rises
The Dark Knight
Amidst the Devil's Wings
Batman
Dead Man Down
Batman
Gangster's Paradise: Jerusalema
Raising Helen
Nine Queens
Synecdoche, New York

In [75]:
import pickle

In [76]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [77]:
pickle.dump(similarity,open('similarity.pkl','wb'))